app:
  build: .
  links:
    - database
  environment:
    - DB_NAME=coalesce
    - ADMIN_PASS=password
  ports:
    - 8080:8080
  expose:
    - 8080
database:
  image: mongo
  command: mongod --smallfiles --quiet --logpath=/dev/null
  ports:
    - 27017:27017
  expose:
    - 27017
